name: Pub Python dist to TestPyPi

on: 
  release:
    types: [published]

jobs:
    build-n-publish:
      name: Build/pub python to testpypi
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master
        - name: Setup Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Build cwtvla
          run: >-
            python setup.py sdist
        - name: Publish to pypi
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.py_pi_deploy }}
